# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: |
    sudo apt-get install postgresql postgresql-contrib libpq-dev --quiet
  displayName: 'sudo apt-get install'

- script: |
    gem install bundler --quiet
    bundle install --retry=3 --jobs=4 --quiet
  displayName: 'bundle install'

- script: bundle exec rake test
  displayName: 'bundle exec rake test'
